#!/bin/sh

rm -f *.o a.out

gcc -std=c18 -pedantic-errors -Werror=pedantic -I./softengine/inc ./softengine/lib/*.c -c -Ofast						&& \
g++ -D_Bool=bool -I./softengine/inc -ljsoncpp $(pkgconf -cflags -libs opencv4) ./softengine/lib/*.cpp -c -Ofast			&& \
g++ -D_Bool=bool -ljsoncpp $(pkgconf -cflags -libs opencv4) -I./softengine/inc *.o main.cpp -Ofast						&& \
./a.out
